### ISSUE TITLE
Receving Failed to query: 'timed out'

### ISSUE THREAD

**Issue by stevarino** [w-gao/py-mcpe-query#6]
Just trying this out on my world (Dedicated 1.18.12.01 - current release at this time) and receiving timed out errors. Tried both domain name and localhost:

```
>>> with mcquery('localhost', timeout=20) as data:
...   print(data)
...
DEBUG:mcquery.query:Connecting to localhost:19132...
DEBUG:mcquery.query:Sending handshake...

DEBUG:mcquery.query:Closing connection...
Traceback (most recent call last):
  File "/mnt/mbe-backup/env/lib/python3.8/site-packages/mcquery/query.py", line 95, in mcquery
    token = soc.recv(65535)[5:-1].decode()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/mnt/mbe-backup/env/lib/python3.8/site-packages/mcquery/query.py", line 116, in mcquery
    raise QueryNetworkError(f"Failed to query: '{msg}'")
mcquery.query.QueryNetworkError: Failed to query: 'timed out'
```

Let me know if you need any further info, happy to share world info privately if it helps debug (or contribute myself if you have any pointers, looking over socket docs nothing stands out to me).

**Comment by w-gao** [comment]
Hi @stevarino, thank you for your report.

Just to make sure, `Dedicated 1.18.12.01` is the official Bedrock server, correct? In that case, `mcquery` won't work. Please refer to https://github.com/w-gao/py-mcpe-stats/issues/7#issuecomment-1003280884 for more details, but essentially this tool uses a protocol that is not supported by all server software.

There is also [`mcstats`](https://github.com/w-gao/py-mcpe-stats), which should work as long as the server is running (but fetches less information), so feel free to try that out.

In the meantime, I ought to update the README to mention this.
